version: '3.9'

services:
  database:
    image: postgres
    container_name: postgresdb
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=exerciciopw
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local